<?php

namespace Database\Seeders;

use App\Models\ArticleBlock;
use Carbon\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ArticleBlocksSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $articleBlocks = [
            [
                'id' => 1,
                'article_id' => 1,
                'position' => 1,
                'type_id' => 1,
                'content' => 'Kapcsolati törések',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 2,
                'article_id' => 1,
                'position' => 2,
                'type_id' => 2,
                'content' => 'és helyreállításuk a mindennapokban',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 3,
                'article_id' => 1,
                'position' => 3,
                'type_id' => 4,
                'content' => 'Zsófi reggel hatkor ébredt, de nem az ébresztőre, hanem a gyerek köhögésére. Aztán láz, 38.6. Gyógyszer, teáskanál, borogatás. Egész nap ugyanaz a körforgás: hőmérő, rajzfilm, hőmérő, tejbegríz. November volt, esett már reggeltől, Zsófiék egész nap a lakásba szorultak. ',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 4,
                'article_id' => 1,
                'position' => 4,
                'type_id' => 6,
                'content' => '/img/article/Meseolvasas.png',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 5,
                'article_id' => 1,
                'position' => 5,
                'type_id' => 4,
                'content' => 'Tizenegykor hívta először a férjét. Pétert. Nem volt nagy dolog, csak hallani akarta a hangját, valami apróságot mondani, hogy „szegény Dani egész délelőtt nyűgös volt, de most elaludt, és tudod, hiányzol.” Péter nem vette fel. Meetingen volt.<bekezdes>Zsófi írt is egy üzenetet. <zold>Nem vádlót, nem szemrehányót, csak egy kis jelzést:</zold> „Képzeld, Dani 38,5. De most alszik. Remélem, neked nem túl húzós a napod.” Elküldte, és bámulta a kijelzőt, de a három pötty nem jelent meg.</bekezdes><bekezdes>Délután kettőkor újra próbálkozott. Újabb hívás, újabb üzenet. „Csak jó lett volna hallani rólad.” Semmi. Péter közben prezentációt tartott, bólogatott a főnöknek, jegyzetelt a laptopjába, pörgött a munkában, a telefonja nem volt az asztalán.</bekezdes>',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 6,
                'article_id' => 1,
                'position' => 6,
                'type_id' => 4,
                'content' => 'Ebédnél, amikor látta Zsófi üzenetét, már épp gépelte volna a választ, de egy kollégája leült mellé beszélgetni, ő pedig visszacsúsztatta a telefont a tálca mellé. Teljesen elfelejtette, hogy nem válaszolt.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 7,
                'article_id' => 1,
                'position' => 7,
                'type_id' => 6,
                'content' => '/img/article/ebed.png',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 8,
                'article_id' => 1,
                'position' => 8,
                'type_id' => 4,
                'content' => 'Hat óra lett, mire hazaért. A sötét lakásban meleg volt,a cipőjét még le se vette, amikor Zsófi már ott állt előtte.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 9,
                'article_id' => 1,
                'position' => 9,
                'type_id' => 3,
                'content' => '<dolt>“Egész nap kerestelek”. - mondta halkan. Nem volt benne kiabálás, csak az a hideg tónus, ami sokkal rosszabb.<bekezdes>“Dolgoztam.” - felelte Péter, mintha ezzel minden el lenne intézve.</bekezdes><bekezdes>“Azért ez nem működik, hogy vissza se hívsz. Itthon vagyok egész nap a beteg gyerekkel, és mi van, ha valami baj van, akkor kit hívjak?” - csattant Zsófi.</bekezdes></dolt>',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 10,
                'article_id' => 1,
                'position' => 10,
                'type_id' => 4,
                'content' => 'Péter bámult a cipőjére. Olyan fáradt volt, hogy az se tudta eldönteni, Zsófinak igaza van-e, csak arra vágyott, hogy lerogyhasson a kanapéra, ahol Dani nézte a tévét.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 11,
                'article_id' => 1,
                'position' => 11,
                'type_id' => 5,
                'content' => 'Zsófi egyetlen mozdulattal felkapta a táskáját.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 12,
                'article_id' => 1,
                'position' => 12,
                'type_id' => 3,
                'content' => '<dolt>“Oldd meg, én elmegyek.”</dolt>',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 13,
                'article_id' => 1,
                'position' => 13,
                'type_id' => 4,
                'content' => 'Péter ott maradt. Levette a cipőjét, levette a kabátját és odalépett a gyerekhez, megpuszilta és visszahúzta rá a takarót, Lerogyott a kanapére, egyszerre kavargott benne a bűntudat, a fáradtság meg a düh.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 14,
                'article_id' => 1,
                'position' => 14,
                'type_id' => 5,
                'content' => 'A zsebében rezgett a telefon. Elővette. Az üzenet most érkezett Zsófitól: Talán így majd megértesz.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 15,
                'article_id' => 1,
                'position' => 15,
                'type_id' => 1,
                'content' => 'Mi az a kapcsolati törés?',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 16,
                'article_id' => 1,
                'position' => 16,
                'type_id' => 4,
                'content' => '<zold>Kapcsolati törésnek azt nevezzük, amikor egy pillanatra megszakad az érzelmi biztonság.</zold> A kapcsolati törés nem a látványos dolgokról szól. Nem kell ajtócsapkodás, nem kell hangos vita. Elég annyi, hogy az egyik fél hirtelen úgy érzi: <dolt>„most nem vagy velem, nem figyelsz rám, nem számítok neked.” </dolt> Ez a pillanat szintén fájdalmas lehet, csak sokszor nehezebb felismerni.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 17,
                'article_id' => 1,
                'position' => 17,
                'type_id' => 6,
                'content' => '/img/article/tores.png',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 18,
                'article_id' => 1,
                'position' => 18,
                'type_id' => 4,
                'content' => 'Sokan gondolják azt, hogy a jó kapcsolat titka, hogy nincsenek benne törések. Pedig ez tévedés. <zold>Törések minden kapcsolatban előfordulnak, még a legerősebbekben is.</zold> Az élet egyszerűen hozza magával a fáradtságot, a stresszt, a félreértéseket. A különbséget nem az jelenti, hogy el tudjuk-e őket kerülni, hanem hogy van-e a felekben elég szeretet egymás felé, hogy tegyenek lépést a helyreállításért. A hosszú távon stabil kapcsolatok abban különböznek, hogy képesek vagytok visszatalálni egymáshoz.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 19,
                'article_id' => 1,
                'position' => 19,
                'type_id' => 1,
                'content' => 'Hétköznapi példák',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 20,
                'article_id' => 1,
                'position' => 20,
                'type_id' => 4,
                'content' => 'A kapcsolati törések legtöbbször nem abból születnek, hogy valaki valami óriási hibát követ el. Sokkal inkább a mindennapokban, apróságokból pattannak ki. ',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 21,
                'article_id' => 1,
                'position' => 21,
                'type_id' => 4,
                'content' => 'Ott van például, amikor elfelejted elhozni a csomagot a postáról. Reggel szólt a párod: „nagyon fontos, ma lejár, ne felejtsd el.” Te persze elfelejtetted. Mire hazaérsz, a csomagot már visszavitték, és a párod arcán látod a csalódottságot. Nem kiabál, de látod, benne ott van:<dolt> „Megint nem számíthattam rád.” </dolt>Ez egy mini törés.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 22,
                'article_id' => 1,
                'position' => 22,
                'type_id' => 4,
                'content' => 'Aztán ott vannak a veszekedések közben elszabadult mondatok. Például amikor dühből odaszúrsz: „Most pont olyan vagy, mint az apád.” Lehet, hogy csak kicsúszott, lehet, hogy akkor és ott igaznak érezted. De <zold>a másikban megnyom egy gombot, és hirtelen nemcsak a jelenről van szó, hanem egy egész gyerekkorról.</zold> Ez már nem apró törés, hanem mély karcolás.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 23,
                'article_id' => 1,
                'position' => 23,
                'type_id' => 4,
                'content' => 'És előfordul, hogy nem a pillanat szüli, hanem a rosszul hangolt időzítés. Elmondtad, hogy júniusban lesz a céges tréning, fontos, nem lehet kihagyni. A párod mégis arra a hétre veszi meg a repülőjegyet a nyári nyaralásra. Ő lelkes, te viszont csak azt érzed: <dolt> „mintha nem is figyelt volna rám.”</dolt> Egy repülőjegy miatt egyszerre omlik rád a figyelmetlenség, a csalódás és az, hogy megint minden bonyolultabb lett a kelleténél.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 24,
                'article_id' => 1,
                'position' => 24,
                'type_id' => 6,
                'content' => '/img/article/repulojegy.png',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 25,
                'article_id' => 1,
                'position' => 25,
                'type_id' => 5,
                'content' => 'Ilyenek a hétköznapi törések. Nem nagy drámák, hanem kicsi repedések a falon. De ha nem javítjuk őket, idővel ugyanúgy szétfeszítik a szerkezetet, mint a nagyobb repedések.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 26,
                'article_id' => 1,
                'position' => 26,
                'type_id' => 1,
                'content' => 'Hogyan néz ki a helyreállítás?',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 27,
                'article_id' => 1,
                'position' => 27,
                'type_id' => 4,
                'content' => '<zold>A valódi helyreállításhoz kell valami, amitől sokan ódzkodunk: az egó félretétele.</zold> Belátni, hogy hibáztunk ugyanis nem egyszerű. Vannak, akik szinte „gyárilag” képtelenek rá. Mem megyünk most bele a mélyebb pszichológiai okaiba ennek, de tény, hogy sokunknak küzdelem kimondani akár magunkban is: <dolt> „Sajnálom, hibáztam.”</dolt> Pedig bizonyos helyzetekben nem elég egy ölelés vagy egy apró gesztus. Nagyobb töréseknél igenis ki kell mondani a szavakat, és mellé oda kell tenni a tetteket is, hogy helyrehozzuk, amit elrontottunk.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 28,
                'article_id' => 1,
                'position' => 28,
                'type_id' => 4,
                'content' => 'Az első példánál – elfelejtetted elhozni a csomagot a postáról, és visszavitték – a helyreállítás nem annyi, hogy kimondod, “Bocs, ezt elbénáztam”. Ki kell tudnod mondani: <dolt> „Tudom, fontos volt, sajnálom, hogy elfelejtettem.”</dolt> És mellé felajánlod: <dolt> „Én intézem el az újrarendelést, ne neked legyen vele dolgod.”</dolt><br><zold> Ez a kettő együtt számít: bocsánatkérés és helyreállítás.</zold><bekezdes>A második helyzetben, amikor vita közben odaszúrsz: <dolt>„Most pont olyan vagy, mint az apád.”</dolt> – az igazi helyreállítás az, ha utána odalépsz, és azt mondod: <dolt> „Nagyon sajnálom, hogy ezt mondtam. Tudom, mennyire bántó, és nem így akartam. Csak elvesztettem a türelmem.”</dolt> És itt sem biztos, hogy elég a szó: utána ell egy gesztus, ami visszavezeti a másikat a biztonságba, egy ölelés, egy odafordulás, valami, amivel megérzi, hogy komolyan gondolod.</bekezdes>',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 29,
                'article_id' => 1,
                'position' => 29,
                'type_id' => 5,
                'content' => 'A harmadik helyzet, a repülőjegyes történet már nagyobb léptékű törés. Ott sem elég pusztán bocsánatot kérni, mert a másik csak akkor érzi, hogy fontos, ha a hibát valahogy tényleg korrigálod.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 30,
                'article_id' => 1,
                'position' => 30,
                'type_id' => 7,
                'content' => '<hasab><hasab-ikon-villanykorte></hasab-ikon-villanykorte><hasab-cim>Praktikus megoldás</hasab-cim><bekezdes-kozep>Módosítod a jegyet, még ha kerül is pénzbe és utánajárásba. Ez mutatja, hogy vállalod a felelősséget.</bekezdes-kozep></hasab><hasab><hasab-ikon-kez></hasab-ikon-kez><hasab-cim>Kompromisszum</hasab-cim><bekezdes-kozep>Ha nem lehet változtatni, a család elutazik, és te a tréning után utánuk mész. Nem tökéletes, de együtt keresitek a kiutat.</bekezdes-kozep></hasab><hasab><hasab-ikon-ora></hasab-ikon-ora><hasab-cim>Radikális gesztus</hasab-cim><bekezdes-kozep>Beteget jelentesz a munkahelyen, és elutazol. Ez erős üzenet: a közös idő fontosabb, mint a munka. Nem hosszú távú stratégia, de egyszer-egyszer hatalmas erőt adhat a kapcsolatnak</bekezdes-kozep></hasab>',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 31,
                'article_id' => 1,
                'position' => 31,
                'type_id' => 5,
                'content' => 'A helyreállítás tehát két részből állhat: bocsánatkérés és cselekvés. A törés nagysága dönti el, hogy mindkettőre szükség van-e.',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 32,
                'article_id' => 1,
                'position' => 32,
                'type_id' => 6,
                'content' => '/img/article/vaza.png',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 33,
                'article_id' => 1,
                'position' => 33,
                'type_id' => 7,
                'content' => '<hasab><hasab-cim>Mini töréseknél</hasab-cim><bekezdes-kozep>(pl. elfelejtett apróságok, közbevágás, egy figyelmetlen mozdulat) sokszor <zold>elég egy gesztus vagy egy ölelés</zold>, mert a másik gyorsan érzi belőle, hogy „itt vagy, fontos vagy nekem”. Ilyenkor nem kell nagy szavakat tenni mellé.</bekezdes-kozep></hasab><hasab><hasab-cim>Közepes töréseknél</hasab-cim><bekezdes-kozep>(pl. figyelmetlenség, elfelejtett csomag, kisebb megszegése a másik kérésének) általában kell <zold>szó és kell tett is</zold>: kimondani, hogy sajnálod, és felajánlani valami jóvátételt (újrarendeled, elintézed). Ez adja a hitelességet.</bekezdes-kozep></hasab><hasab><hasab-cim>Nagy töréseknél</hasab-cim><bekezdes-kozep>(pl. bántó mondat, kiabálás, rossz időzítéssel hozott fontos döntés, elfelejtett ígéret) <zold>szinte biztos, hogy mindkettő kell</zold>: a bocsánatkérés kimondva és valami cselekvés, ami visszaépíti a bizalmat. Itt önmagában egy „bocs” vagy egy ölelés kevés lenne.</bekezdes-kozep></hasab>',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 34,
                'article_id' => 1,
                'position' => 34,
                'type_id' => 1,
                'content' => 'Egy párkapcsolat olyan, mint a wifi',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 35,
                'article_id' => 1,
                'position' => 35,
                'type_id' => 2,
                'content' => 'néha elmegy a jel, és újra kell kapcsolódni',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 36,
                'article_id' => 1,
                'position' => 36,
                'type_id' => 5,
                'content' => 'Minden sikeres helyreállítás kicsit olyan, mint egy újabb öltés a kapcsolatotok szövetében. Ha mindig képesek vagytok összevarrni, a szövet nem gyengül, hanem erősebb lesz. Ha viszont a helyreállítás elmarad, a sérelmek lassan egymásra rakódnak. ',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 37,
                'article_id' => 1,
                'position' => 37,
                'type_id' => 4,
                'content' => 'A törések és a helyreállítások messze túlmutatnak az adott pillanaton. Egy gyerek például pontosan ebből tanulja meg, hogy egy konfliktus nem a világ vége. ',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 38,
                'article_id' => 1,
                'position' => 38,
                'type_id' => 4,
                'content' => 'Aki gyerekként sosem kapott bocsánatkérést, annak gyógyító erejű, ha a párja ki tudja mondani: „Sajnálom.” De másik oldalról is: katartikus élmény, ha valaki életében először ki tudja mondani, hogy “Bocsánat, hibáztam” és látja, hogy nem dől össze a világ, nem lesz ettől kevesebb a párja szemében. <zold>Ezek a pillanatok írják át a régi mintáitokat.</zold>',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'id' => 39,
                'article_id' => 1,
                'position' => 39,
                'type_id' => 4,
                'content' => 'Zsófi és Péter története tipikus: mindennapi helyzetekből: beteg gyerek, túlterhelt munka, elfelejtett üzenetek, könnyen lesz kapcsolati törés. A döntő nem az, hányszor történik ilyen,hanem hogy <zold>megvan-e bennetek a képesség a helyreállításra: kimondani a bocsánatkérést, keresni a megoldást, és újra egymás felé fordulni.</zold>',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ];

        foreach ($articleBlocks as $articleBlock) {
            ArticleBlock::create($articleBlock);
        }
    }
}
